work on start/stop/restart scripts

diff --git a/startminimy b/startminimy
--- a/startminimy
+++ b/startminimy
@@ -3,7 +3,24 @@
 # startminimy - start the minimy personal voice assistant and music player
 # 
 #+--------------------------------------------------------------------------+
-function mountFStmpfs
+function umountTmpfs
+# Unmount a temporary file system if it is mounted
+# Arg 1: file system to umount
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  fileSystem=$1
+  echo "Unmounting tmpfs file system $fileSystem..."
+  fsType=`mount | grep $fileSystem | awk '{print $1}'` # check if it's mounted
+  if [ "$fsType" = "tmpfs" ]; then
+    sudo umount $fileSystem
+  fi
+ }                                         # umountTmpfs()
+
+#+--------------------------------------------------------------------------+
+function mountTmpfs
 # Mount a file system in a tmpfs using systemd .mount files
 # Arg 1    : systemd .mount file to use
 # Args 2-n : description of the file system
@@ -31,28 +48,26 @@ function mountFStmpfs
   else
     echo "$cmd was successful"
   fi
- }                                         # mountFStmpfs()
+ }                                         # mountTmpfs()
 
 #+--------------------------------------------------------------------------+
-function mountLogDirs
+function mountUmountDirs
 # make log files directories tmpfs's to prolong the life of the micro-SD card
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  mountFStmpfs home-$USER-minimy-logs.mount Minimy log directory
-  mountFStmpfs var-log.mount /var/log
-  if [ ! -d /var/log/mpd ]; then           # mpd needs a log file to start
-    sudo mkdir /var/log/mpd
-    sudo touch /var/log/mpd/mpd.log
-  fi
+  umountTmpfs $HOME/minimy/logs
+  mountTmpfs home-$USER-minimy-logs.mount Minimy log directory
 
   # mount a tmpfs over minimy/tmp and create three subdirectories
-  mountFStmpfs home-$USER-minimy-tmp.mount Minimy temp directory
+  echo
+  umountTmpfs $HOME/minimy/tmp
+  mountTmpfs home-$USER-minimy-tmp.mount Minimy temp directory
   sleep 1
   mkdir $baseDir/tmp/save_audio $baseDir/tmp/save_text $baseDir/tmp/save_tts
- }
+ }                                         # mountUmountDirs()
 
 #+--------------------------------------------------------------------------+
 function startSystem 
@@ -75,10 +90,12 @@ function startSystem
     echo "It appears Minimy is already running!"
     exit 1
   fi
-  echo 'System Starting ...'               # start Minimy
+  echo
+  echo "Starting base components ..."               # start Minimy
   cd $baseDir
   cat install/mmconfig.yml | grep -v "AWS" | grep -v "Goog"
-  echo 'Start Local STT Server'
+  echo
+  echo "Starting Local STT Server ..."
   which deactivate >/dev/null
   if [ $? = 0 ]; then
     deactivate
@@ -91,7 +108,8 @@ function startSystem
     deactivate
   fi
   cd ../../../../..
-  echo 'Starting Local TTS Server ...'
+  echo
+  echo "Starting Local TTS Server ..."
   cd framework/services/tts/local/mimic3
   deactivate
   source .venv/bin/activate
@@ -105,20 +123,24 @@ function startSystem
   export PYTHONPATH=`pwd`
   export SVA_BASE_DIR=`pwd`
   export GOOGLE_APPLICATION_CREDENTIALS="/home/pi/minimy/install/my-google-key.json"
-  echo 'Starting Message Bus ...'
+  echo
+  echo "Starting Message Bus ..."
   cd bus
   python3 MsgBus.py &
   cd ..
   sleep 2
-  echo 'Starting System Skill ...'
+  echo
+  echo "Starting System Skill ..."
   cd skills/system_skills
   python3 skill_system.py &
   sleep 1
   cd ../../
-  echo 'Starting Intent Service ...'
+  echo
+  echo "Starting Intent Service ..."
   python3 framework/services/intent/intent.py &
   sleep 2 
-  echo 'Starting Media Service ...'
+  echo
+  echo "Starting Media Service ..."
   python3 framework/services/output/media_player.py &
   python3 framework/services/tts/tts.py &
   python3 framework/services/stt/stt.py &
@@ -156,8 +178,8 @@ function loadSystemSkills
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  echo ' '
-  echo 'Start System Skills ...'
+  echo 
+  echo "Starting System Skills ..."
   cd $baseDir
   python3 skills/system_skills/skill_fallback.py &
   python3 skills/system_skills/skill_media.py &
@@ -174,15 +196,15 @@ function loadUserSkills
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  echo ' '
-  echo 'Start User Skills'
+  echo " "
+  echo "Starting User Skills ..."
   cd $baseDir/skills/user_skills
   loadOneSkill help Help skill
   # rfm, youtube and npr_news skills have been incorporated into the mpc skill
   # loadOneSkill ../rfm RFM skill
   # loadOneSkill ../youtube YouTube skill 
   # loadOneSkill ../npr_news NPR News skill 
-  # do not load the Home Assistant skill for now'
+  # do not load the Home Assistant skill for now
   # loadOneSkill ../ha_skill Home Assistant skill
   loadOneSkill ../email Email skill
   loadOneSkill ../wiki Wiki skill
@@ -195,6 +217,22 @@ function loadUserSkills
  }                                         # loadUserSkills()
 
 #+--------------------------------------------------------------------------+
+function loadButtons
+# load the buttons daemon 
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  echo
+  echo "Starting buttons ..."
+  cd $baseDir
+  source venv_ngv/bin/activate
+  python3 framework/services/input/buttons.py &
+  echo
+ }                                         # loadButtons()
+
+#+--------------------------------------------------------------------------+
 function loadMic
 # load the microphone 
 #+--------------------------------------------------------------------------+
@@ -202,7 +240,7 @@ function loadMic
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  echo 'Finally, start the mic'
+  echo "Finally, starting the mic ..."
   cd $baseDir
   source venv_ngv/bin/activate
   python3 framework/services/input/mic.py &
@@ -211,13 +249,18 @@ function loadMic
 
 # main()
 baseDir="$HOME/minimy"
+if [ ! -d $baseDir ]; then                 # base dir not found
+  echo "ERROR: directory $baseDir not found"
+  exit 1
+fi
 export PYTHONPATH="$baseDir:$baseDir/venv_ngv/lib/python3.10/site-packages"
 export SVA_BASE_DIR="$baseDir"
 
-mountLogDirs $@                            # mount tmpfs's over log mount tmpfs's over log directories
+mountUmountDirs                            # unmount then remount logs and tmp dirs as tmpfs's
 startSystem
 loadSystemSkills 
 loadUserSkills 
+loadButtons
 loadMic 
-echo '** System Started **'
+echo "** System Started **"
 
